
obj-$(CONFIG_STEELY_TIMERBENCH) += steely_timerbench.o
obj-$(CONFIG_STEELY_SWITCHTEST) += steely_switchtest.o
obj-$(CONFIG_STEELY_RTDMTEST)   += steely_rtdmtest.o

steely_timerbench-y := timerbench.o

steely_switchtest-y := switchtest.o

steely_rtdmtest-y := rtdmtest.o
