
ccflags-y += -Ikernel

obj-$(CONFIG_STEELY) += steely.o

steely-y :=		\
	clock.o		\
	cond.o		\
	corectl.o	\
	event.o		\
	io.o		\
	memory.o	\
	monitor.o	\
	mqueue.o	\
	mutex.o		\
	nsem.o		\
	process.o	\
	sched.o		\
	sem.o		\
	signal.o	\
	timer.o		\
	timerfd.o
