
obj-$(CONFIG_STEELY_RTIPC) += steely_rtipc.o

steely_rtipc-y := rtipc.o

steely_rtipc-$(CONFIG_STEELY_RTIPC_XDDP) += xddp.o
steely_rtipc-$(CONFIG_STEELY_RTIPC_IDDP) += iddp.o
steely_rtipc-$(CONFIG_STEELY_RTIPC_BUFP) += bufp.o
